# Generated by Django 3.2.6 on 2022-05-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('balance_time', models.DateTimeField()),
                ('owner_earning', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parking_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('avilable', models.IntegerField()),
                ('filled', models.IntegerField()),
                ('booking_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('balance', models.IntegerField(default=100)),
                ('book', models.BooleanField(default=False)),
                ('open_gate', models.BooleanField(default=False)),
                ('inside_gate', models.BooleanField(default=False)),
            ],
        ),
    ]
