# Generated by Django 3.2.6 on 2022-05-15 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance_history',
        ),
    ]
