# Generated by Django 3.2.6 on 2022-05-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_balance_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('balance_time', models.DateTimeField()),
                ('owner_earning', models.IntegerField()),
            ],
        ),
    ]
