# Generated by Django 3.2.6 on 2022-05-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_balance_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_history',
            name='balance_added',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
